name: docker-image-save
version: 1.6.19
summary: Download zip compressed Docker images.
description: |
  DockerImageSave will download Docker images from Dockerhub using a 3rd party server. Can be used in countries with restricted access to Dockerhub.

confinement: strict
base: core18

parts:
  docker-image-save:
    plugin: go
    source: https://github.com/jadolg/DockerImageSave
    source-type: git
    build-packages:
      - gcc

apps:
  docker-image-save:
    command: bin/DockerImageSave
    plugs:
      - home
      - removable-media
      - network
